name: course_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.7
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  path_provider: ^2.1.1
  firebase_auth: ^5.5.3
  firebase_dart: ^1.3.6
  hive_generator: ^2.0.1
  firebase_core: ^3.13.0
  image_picker: ^1.0.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
