// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7Bf4EJ_QB__Q9nNXPi6xcIefwsdwQms',
    appId: '1:878690816525:web:0d37d0713e274901cafb44',
    messagingSenderId: '878690816525',
    projectId: 'mobile-feaf5',
    authDomain: 'mobile-feaf5.firebaseapp.com',
    storageBucket: 'mobile-feaf5.firebasestorage.app',
    measurementId: 'G-1QZ12L7R9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgy68Ptj2O0aoBHvV8-NuIBmuxLjUqYbc',
    appId: '1:878690816525:android:d01197156733f512cafb44',
    messagingSenderId: '878690816525',
    projectId: 'mobile-feaf5',
    storageBucket: 'mobile-feaf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF21XbuMopImJj9-K17TSQP3ovNbErZX8',
    appId: '1:878690816525:ios:f781167f8f34c6f5cafb44',
    messagingSenderId: '878690816525',
    projectId: 'mobile-feaf5',
    storageBucket: 'mobile-feaf5.firebasestorage.app',
    iosBundleId: 'com.Boudycar.Motorly.courseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF21XbuMopImJj9-K17TSQP3ovNbErZX8',
    appId: '1:878690816525:ios:f781167f8f34c6f5cafb44',
    messagingSenderId: '878690816525',
    projectId: 'mobile-feaf5',
    storageBucket: 'mobile-feaf5.firebasestorage.app',
    iosBundleId: 'com.Boudycar.Motorly.courseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7Bf4EJ_QB__Q9nNXPi6xcIefwsdwQms',
    appId: '1:878690816525:web:0cbadc48cae2c05ccafb44',
    messagingSenderId: '878690816525',
    projectId: 'mobile-feaf5',
    authDomain: 'mobile-feaf5.firebaseapp.com',
    storageBucket: 'mobile-feaf5.firebasestorage.app',
    measurementId: 'G-WF4NRSCDG7',
  );
}
